
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmclujwtwuzscfqbzfxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtY2x1and0d3V6c2NmcWJ6ZnhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjc0NTYsImV4cCI6MjA2MjcwMzQ1Nn0.x7ZXita8X6zfYNbEc29Hd3ZhSxXRaqBlqUyduedUK7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: false, // Don't persist session as we're using mock users
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  }
);
